### PR TITLE
Elixir 1.11 Compatibility & CI Tests

### PR DESCRIPTION
**Pull request by iloveitaly**
Also added a big readme update.

### CODE REVIEW

**Comment by jarednorman** [comment]
I don't think this project is currently maintained. @avdi left maintenance to me, but I'm no longer available to do so. Best of luck.

**Comment by iloveitaly** [comment]
@jarednorman are you able to add me as a maintainer?

**Comment by jarednorman** [comment]
Sorry, I do not possess admin powers.

**Comment by iloveitaly** [comment]
@avdi could you add me as a maintainer on this repo and on hex? https://hex.pm/users/iloveitaly

**Comment by avdi** [comment]
@iloveitaly Github invite sent! I don't think I have a Hex login though, I don't think that was a thing back when I started this project 😅

**Pull request merged**
